name: ci-dotnet-samples

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "samples/**/*.cs"

jobs:
  generate:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          only-changed-files: "true"